# Generated by Django 5.2.10 on 2026-01-27 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAGPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('industrial', 'Industrial'), ('supply', 'Supply Chain'), ('people', 'People'), ('tasks', 'Tasks'), ('alerts', 'Alerts')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('endpoint_url', models.URLField(help_text="Backend endpoint for this RAG pipeline's data source")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='RAGQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript_id', models.UUIDField(help_text='ID of the transcript entry that triggered this query')),
                ('query_text', models.TextField()),
                ('intent', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='layer2.ragpipeline')),
            ],
            options={
                'verbose_name_plural': 'RAG Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(help_text='Query execution time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='layer2.ragquery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
